spring:
  application:
    name: invoiceflow

  datasource:
    url: jdbc:postgresql://localhost:5432/invoiceflow
    username: invoiceflow
    password: invoiceflow
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
