package com.example.invoiceflow.audit;

public enum AuditAction {
    LOGIN_SUCCESS,
    LOGIN_FAILED,
    PASSWORD_RESET_REQUESTED,
    PASSWORD_CHANGED,
    TWO_FA_ENABLED,
    TWO_FA_DISABLED,

    INVOICE_SENT,
    INVOICE_CANCELLED,
    INVOICE_PAYMENT_RECORDED,

    CREDIT_NOTE_ISSUED,

    STRIPE_PAYMENT_CONFIRMED,

    ADMIN_USER_STATUS_CHANGED,
    ADMIN_USER_ROLE_CHANGED,
    ADMIN_USER_PASSWORD_RESET_SENT,

    ACCOUNT_DELETED
}
